version: '3'

services:

    app:
        build: ./node
        container_name: app
        networks:
            - node-network
        volumes:
            - ./node/api:/app/api
        tty: true
        ports:
            - "3000"
        depends_on: 
            - db

    db:
        image: mysql:5.7
        command: --innodb-use-native-aio=0
        container_name: db
        restart: always
        tty: true
        volumes: 
            - ./mysql/data:/var/lib/mysql
            - ./mysql/init:/docker-entrypoint-initdb.d/:ro
        environment: 
            - MYSQL_DATABASE=nodedb
            - MYSQL_ROOT_PASSWORD=root
        networks:
            - node-network
    nginx:
        container_name: nginx-server
        restart: always
        build: ./nginx
        networks:
            - node-network
        ports:
            - "8080:80"
        depends_on: 
            - app

networks: 
    node-network:
        driver: bridge